### ISSUE TITLE
Wrong require statement

### ISSUE THREAD

**Issue by v-kolesnikov** [rom-rb/rom-yaml#10]
Script for reproduction:

```ruby
#!/usr/bin/env ruby

require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'

  gem 'rom-yaml', '~> 2.0.0rc1'
end

require 'rom-yaml'
```

Output
```Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies...
Using bundler 1.16.0.pre.3
Using concurrent-ruby 1.0.5
Using dry-configurable 0.7.0
Using dry-container 0.6.0
Using dry-core 0.4.0
Using dry-equalizer 0.2.0
Using dry-initializer 2.3.0
Using dry-logic 0.4.2
Using inflecto 0.0.2
Using dry-types 0.12.1
Using ice_nine 0.11.2
Using dry-struct 0.3.1
Using transproc 1.0.2
Using rom-mapper 1.0.2
Using rom-core 4.0.2
Using rom-yaml 2.0.0.rc1
/Users/vkolesnikov/.rvm/gems/ruby-2.4.2/gems/rom-yaml-2.0.0.rc1/lib/rom/yaml.rb:1:in `require': cannot load such file -- rom (LoadError)
	from /Users/vkolesnikov/.rvm/gems/ruby-2.4.2/gems/rom-yaml-2.0.0.rc1/lib/rom/yaml.rb:1:in `<top (required)>'
	from /Users/vkolesnikov/.rvm/gems/ruby-2.4.2/gems/rom-yaml-2.0.0.rc1/lib/rom-yaml.rb:1:in `require'
	from /Users/vkolesnikov/.rvm/gems/ruby-2.4.2/gems/rom-yaml-2.0.0.rc1/lib/rom-yaml.rb:1:in `<top (required)>'
	from /Users/vkolesnikov/.rvm/gems/ruby-2.4.2/gems/bundler-1.16.0.pre.3/lib/bundler/runtime.rb:83:in `require'
	from /Users/vkolesnikov/.rvm/gems/ruby-2.4.2/gems/bundler-1.16.0.pre.3/lib/bundler/runtime.rb:83:in `block (2 levels) in require'
	from /Users/vkolesnikov/.rvm/gems/ruby-2.4.2/gems/bundler-1.16.0.pre.3/lib/bundler/runtime.rb:78:in `each'
	from /Users/vkolesnikov/.rvm/gems/ruby-2.4.2/gems/bundler-1.16.0.pre.3/lib/bundler/runtime.rb:78:in `block in require'
	from /Users/vkolesnikov/.rvm/gems/ruby-2.4.2/gems/bundler-1.16.0.pre.3/lib/bundler/runtime.rb:67:in `each'
	from /Users/vkolesnikov/.rvm/gems/ruby-2.4.2/gems/bundler-1.16.0.pre.3/lib/bundler/runtime.rb:67:in `require'
	from /Users/vkolesnikov/.rvm/gems/ruby-2.4.2/gems/bundler-1.16.0.pre.3/lib/bundler/inline.rb:70:in `gemfile'
	from test.rb:5:in `<main>'
```

I assume we don't need to require rom, but rom-core only. In other case we should add 'rom' as runtime-dependency for rom-yaml.

**Comment by v-kolesnikov** [comment]
Closed by #9
